### ISSUE TITLE
sourcemarker does not support IntelliJ community edition

### ISSUE THREAD

**Issue by juhanishen** [sourceplusplus/SourceMarker#280]
Why does SourceMarker not support IntelliJ community edition?

**Comment by BFergerson** [comment]
There's no reason it shouldn't work for the community edition.
https://plugins.jetbrains.com/plugin/15407-sourcemarker/versions/stable/102493

Is there a particular issue you're facing that makes you think it doesn't support the community edition?

**Comment by juhanishen** [comment]
I installed SourceMarker in my own computer 's  IntelliJ (Community edition) and link to our company's internal network's skywalking instance. It pop up following exception which makes me think SourceMarker does not support intelliJ community edition.

java.time.DateTimeException: Zone offset hours not in valid range: value 800 is not in the range -18 to 18
	at java.base/java.time.ZoneOffset.validate(ZoneOffset.java:364)
	at java.base/java.time.ZoneOffset.ofHoursMinutesSeconds(ZoneOffset.java:317)
	at java.base/java.time.ZoneOffset.ofHours(ZoneOffset.java:283)
	at com.sourceplusplus.monitor.skywalking.SkywalkingClient.getDuration(SkywalkingClient.kt:156)
	at com.sourceplusplus.monitor.skywalking.SkywalkingClient.getDuration(SkywalkingClient.kt:152)
	at com.sourceplusplus.monitor.skywalking.bridge.ServiceBridge$start$2$1.invokeSuspend(ServiceBridge.kt:29)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.vertx.kotlin.coroutines.VertxCoroutineExecutor.execute(VertxCoroutine.kt:214)
	at kotlinx.coroutines.ExecutorCoroutineDispatcherBase.dispatch(Executors.kt:94)
	at kotlinx.coroutines.internal.DispatchedContinuationKt.resumeCancellableWith(DispatchedContinuation.kt:305)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable(Cancellable.kt:30)
	at kotlinx.coroutines.intrinsics.CancellableKt.startCoroutineCancellable$default(Cancellable.kt:27)
	at kotlinx.coroutines.CoroutineStart.invoke(CoroutineStart.kt:109)
	at kotlinx.coroutines.AbstractCoroutine.start(AbstractCoroutine.kt:158)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch(Builders.common.kt:56)
	at kotlinx.coroutines.BuildersKt.launch(Unknown Source)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.launch$default(Builders.common.kt:49)
	at kotlinx.coroutines.BuildersKt.launch$default(Unknown Source)
	at com.sourceplusplus.monitor.skywalking.bridge.ServiceBridge$start$2.handle(ServiceBridge.kt:27)
	at com.sourceplusplus.monitor.skywalking.bridge.ServiceBridge$start$2.handle(ServiceBridge.kt:20)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:919)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.handle(VertxImpl.java:887)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.execute(EventLoopContext.java:43)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:229)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:221)
	at io.vertx.core.impl.VertxImpl$InternalTimerHandler.run(VertxImpl.java:913)
	at io.netty.util.concurrent.PromiseTask.runTask(PromiseTask.java:98)
	at io.netty.util.concurrent.ScheduledFutureTask.run(ScheduledFutureTask.java:176)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by BFergerson** [comment]
I've fixed this issue in version 0.1.1. Issue involved incorrectly parsing timezones. v0.1.1 should be available to download/upgrade through JetBrains marketplace by tomorrow. Otherwise you can download it directly from [here](https://github.com/sourceplusplus/SourceMarker/releases/tag/v0.1.1). Thanks for opening this issue.
