### ISSUE TITLE
NullPointException happened

### ISSUE THREAD

**Issue by juhanishen** [sourceplusplus/SourceMarker#282]
java.lang.NullPointerException
	at com.sourceplusplus.monitor.skywalking.SkywalkingClient.searchEndpoint(SkywalkingClient.kt:130)
	at com.sourceplusplus.monitor.skywalking.SkywalkingClient$searchEndpoint$1.invokeSuspend(SkywalkingClient.kt)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at io.vertx.kotlin.coroutines.VertxCoroutineExecutor$execute$1.handle(VertxCoroutine.kt:212)
	at io.vertx.kotlin.coroutines.VertxCoroutineExecutor$execute$1.handle(VertxCoroutine.kt:208)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by BFergerson** [comment]
What version of Apache SkyWalking are you using?

**Comment by juhanishen** [comment]
apache-skywalking-apm-es7-6.6.0.tar.gz

**Comment by BFergerson** [comment]
@juhanishen, thanks for this information.
I've yet to determine the oldest version SourceMarker works with. I've primarily been testing it with SkyWalking 8.x.

I'll close this ticket once I've updated the documentation with the lowest supported version of SkyWalking.

**Comment by BFergerson** [comment]
@juhanishen, I've updated the documentation to reflect SourceMarker only works with SkyWalking 8+. It appears to have partial support for SkyWalking 7 as well, but SkyWalking 8+ is going to be the recommended version for SourceMarker.

Thanks again for pointing out the issues you see with this project.
