### ISSUE TITLE
MethodGutterMark.getLineNumber() error

### ISSUE THREAD

**Issue by BFergerson** [sourceplusplus/SourceMarker#8]
```
2020-04-03 14:21:12,320 [ 154975]  ERROR - llij.ide.plugins.PluginManager - IntelliJ IDEA 2020.1 EAP  Build #IC-201.6073.9 
2020-04-03 14:21:12,320 [ 154975]  ERROR - llij.ide.plugins.PluginManager - JDK: 11.0.6; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o 
2020-04-03 14:21:12,320 [ 154975]  ERROR - llij.ide.plugins.PluginManager - OS: Windows 10 
2020-04-03 14:21:12,320 [ 154975]  ERROR - llij.ide.plugins.PluginManager - Plugin to blame: Source++ version: 0.2.5 
2020-04-03 14:21:12,320 [ 154975]  ERROR - llij.ide.plugins.PluginManager - Last Action: ShowIntentionActions 
2020-04-03 14:21:43,233 [ 185888]  ERROR - llij.ide.plugins.PluginManager - Element: class com.intellij.psi.impl.source.tree.java.PsiIdentifierImpl #JAVA  because: different providers: com.intellij.psi.SingleRootFileViewProvider{vFile=file://C:/Users/ferge/IdeaProjects/Java-SPP-Maven-Test/src/main/java/com/company/JavaErrorExample.java, content=VirtualFileContent{size=746}, eventSystemEnabled=true}(23ff28be); com.intellij.psi.SingleRootFileViewProvider{vFile=file://C:/Users/ferge/IdeaProjects/Java-SPP-Maven-Test/src/main/java/com/company/JavaErrorExample.java, content=VirtualFileContent{size=746}, eventSystemEnabled=true}(27bef309)
invalidated at: see attachment; com.intellij.psi.impl.source.tree.java.PsiIdentifierImpl:IDENTIFIER / com.intellij.psi.impl.source.tree.java.MethodElement:METHOD / com.intellij.psi.impl.source.tree.java.ClassElement:CLASS / com.intellij.psi.impl.source.tree.java.JavaFileElement:java.FILE 
com.intellij.psi.PsiInvalidElementAccessException: Element: class com.intellij.psi.impl.source.tree.java.PsiIdentifierImpl #JAVA  because: different providers: com.intellij.psi.SingleRootFileViewProvider{vFile=file://C:/Users/ferge/IdeaProjects/Java-SPP-Maven-Test/src/main/java/com/company/JavaErrorExample.java, content=VirtualFileContent{size=746}, eventSystemEnabled=true}(23ff28be); com.intellij.psi.SingleRootFileViewProvider{vFile=file://C:/Users/ferge/IdeaProjects/Java-SPP-Maven-Test/src/main/java/com/company/JavaErrorExample.java, content=VirtualFileContent{size=746}, eventSystemEnabled=true}(27bef309)
invalidated at: see attachment; com.intellij.psi.impl.source.tree.java.PsiIdentifierImpl:IDENTIFIER / com.intellij.psi.impl.source.tree.java.MethodElement:METHOD / com.intellij.psi.impl.source.tree.java.ClassElement:CLASS / com.intellij.psi.impl.source.tree.java.JavaFileElement:java.FILE
	at com.intellij.psi.impl.source.tree.LeafPsiElement.invalid(LeafPsiElement.java:102)
	at com.intellij.psi.impl.source.tree.LeafPsiElement.getContainingFile(LeafPsiElement.java:86)
	at com.sourceplusplus.marker.source.mark.gutter.MethodGutterMark.getLineNumber(MethodGutterMark.kt:75)
```

**Comment by BFergerson** [comment]
Works better in SourceMarker example plugins but not in SPP

**Comment by BFergerson** [comment]
Need to do a maven config file change and then reimport (control shift O). Should test on windows/linux
